production:
  primary:
    adapter: postgresql
    url: <%= ENV['DATABASE_URL'] %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

  cable:
    adapter: postgresql
    url: <%= ENV['DATABASE_URL'] %>
    pool: 5
